### ISSUE TITLE
Cannot get it running on Windows

### ISSUE THREAD

**Issue by astenman** [latex-lsp/texlab#13]
I tried to use this software in Emacs using lsp-mode. But it does not work.

'''
mar 31, 2019 10:01:59 EM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.util.NoSuchElementException: Collection contains no element matching the predicate.
java.util.concurrent.CompletionException: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at kotlinx.coroutines.future.CompletableFutureCoroutine.onCompletedExceptionally(Future.kt:61)
	at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal$kotlinx_coroutines_core(AbstractCoroutine.kt:106)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:305)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:230)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:799)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:742)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at texlab.provider.FeatureRequest.<init>(FeatureRequest.kt:16)
	at texlab.LatexLanguageServer$runFeature$2.invokeSuspend(LatexLanguageServer.kt:428)
	at texlab.LatexLanguageServer$runFeature$2.invoke(LatexLanguageServer.kt)
	at texlab.WorkspaceActor.withWorkspace(WorkspaceActor.kt:34)
	at texlab.WorkspaceActor$withWorkspace$1.invokeSuspend(WorkspaceActor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	... 4 more

Exception in thread "DefaultDispatcher-worker-8" java.lang.IllegalStateException: directory.resolve(MIKTEX              .listFiles() must not be null
	at texlab.resolver.LatexResolver$Companion.readDatabase(LatexResolver.kt:97)
	at texlab.resolver.LatexResolver$Companion.create(LatexResolver.kt:35)
	at texlab.LatexLanguageServer$resolver$1.invokeSuspend(LatexLanguageServer.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
mar 31, 2019 10:02:00 EM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.util.NoSuchElementException: Collection contains no element matching the predicate.
java.util.concurrent.CompletionException: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at kotlinx.coroutines.future.CompletableFutureCoroutine.onCompletedExceptionally(Future.kt:61)
	at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal$kotlinx_coroutines_core(AbstractCoroutine.kt:106)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:305)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:230)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:799)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:742)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at texlab.provider.FeatureRequest.<init>(FeatureRequest.kt:16)
	at texlab.LatexLanguageServer$runFeature$2.invokeSuspend(LatexLanguageServer.kt:428)
	at texlab.LatexLanguageServer$runFeature$2.invoke(LatexLanguageServer.kt)
	at texlab.WorkspaceActor.withWorkspace(WorkspaceActor.kt:34)
	at texlab.WorkspaceActor$withWorkspace$1.invokeSuspend(WorkspaceActor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	... 4 more

'''
latex and kpsewhich is on the path ...

**Comment by efoerster** [comment]
Thanks for report. Which TeX distribution are you using? Can you please provide the output of `latex -version`? At the moment we are having trouble to reproduce this.

**Comment by Maswor** [comment]
It seems like there was problem communicating between the language-client and the server (based on the org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError). By the way, thank you for the project, please post it in r/vscode and r/neovim. Your work should get more attention!

**Comment by astenman** [comment]
I am using the following TeX distro

```
C:\Users\anste.NIRADYNAMICS>latex --version
MiKTeX-pdfTeX 2.9.6668 (1.40.19) (MiKTeX 2.9.6800 64-bit)
Copyright (C) 1982 D. E. Knuth, (C) 1996-2018 Han The Thanh
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.56.1; using libcurl/7.56.1 WinSSL
compiled with expat version 2.2; using expat_2.2.0
compiled with jpeg version 9.2
compiled with liblzma version 50020032; using 50020032
compiled with libpng version 1.6.34; using 1.6.34
compiled with libressl version LibreSSL 2.5.3; using LibreSSL 2.5.3
compiled with MiKTeX Application Framework version 3.6802; using 3.6802
compiled with MiKTeX Core version 8.6811; using 8.6811
compiled with MiKTeX Archive Extractor version 1.6300; using 1.6300
compiled with MiKTeX Package Manager version 3.6810; using 3.6810
compiled with poppler version 0.60.1
compiled with uriparser version 0.8.4
compiled with zlib version 1.2.11; using 1.2.11
```

**Comment by astenman** [comment]
I updated from Java 8 to Java 11. Now I get the following error

```
apr 10, 2019 8:09:44 EM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.util.NoSuchElementException: Collection contains no element matching the predicate.
java.util.concurrent.CompletionException: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at kotlinx.coroutines.future.CompletableFutureCoroutine.onCompletedExceptionally(Future.kt:61)
	at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal$kotlinx_coroutines_core(AbstractCoroutine.kt:106)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:305)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:230)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:799)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:742)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at texlab.provider.FeatureRequest.<init>(FeatureRequest.kt:16)
	at texlab.LatexLanguageServer$runFeature$2.invokeSuspend(LatexLanguageServer.kt:428)
	at texlab.LatexLanguageServer$runFeature$2.invoke(LatexLanguageServer.kt)
	at texlab.WorkspaceActor.withWorkspace(WorkspaceActor.kt:34)
	at texlab.WorkspaceActor$withWorkspace$1.invokeSuspend(WorkspaceActor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	... 4 more
```

**Comment by efoerster** [comment]
Thanks for the log. The issue is most likely caused by requests that are sent out of order from the client. We made the server more robust for those cases. Could you try again with the newest version?

**Comment by astenman** [comment]
Thank you!

With version v0.4.2 it does not bomb explicitly, but I still get exceptions. I have attached two files:

- lsp.txt: A log of the lsp messages between emacs and texlab
- stderr.txt: The stderr output from texlab.

I have just used the standard setting in lsp-mode in Emacs. Perhaps it needs to be initialized differently?

[lsp.txt](https://github.com/latex-lsp/texlab/files/3079082/lsp.txt)
[stderr.txt](https://github.com/latex-lsp/texlab/files/3079084/stderr.txt)

**Comment by efoerster** [comment]
The attached log shows that Emacs sends a `TextDocument` with a `languageId` of `null`. This violates the LSP specification. It seems that the lsp-mode is not configured correctly.

You might want look into this project: https://github.com/ROCKTAKEY/lsp-latex

**Comment by astenman** [comment]
Thank you for the info.

I got the same behavior with "https://github.com/ROCKTAKEY/lsp-latex". I need to add the line
```
(push (cons 'latex-mode "latex") lsp-language-id-configuration)
```
to get it working.

Now I just get the following stderr log.

```
Exception in thread "DefaultDispatcher-worker-3" java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject
	at texlab.LatexLanguageServer.runLinter(LatexLanguageServer.kt:477)
	at texlab.LatexLanguageServer$didOpen$$inlined$apply$lambda$1.invokeSuspend(LatexLanguageServer.kt:210)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by efoerster** [comment]
Can you try out the newest commit by running `./gradlew shadowJar` in the repository directory?
The JAR is then located at `./build/libs/texlab.jar`.

**Comment by astenman** [comment]
With the latest version from git it seems to be running fine without exceptions. Thank you!

But it is very slow. Tab completion takes several seconds. I will dig into this later.

**Comment by pfoerster** [comment]
Are there any updates on this?
We have rewritten the server in Rust and made some performance improvements.
That's why, it should be a lot faster than the Kotlin version.
