### ISSUE TITLE
Hovering over bibtex entry with crossref field fails

### ISSUE THREAD

**Issue by nicolasmeric** [latex-lsp/texlab#16]
Hovering over bibtex entry with crossref field fails with an exception:

> Exception in thread "DefaultDispatcher-worker-6" org.jbibtex.ObjectResolutionException
	at org.jbibtex.BibTeXParser.checkCrossReferenceResolution(BibTeXParser.java:130)
	at org.jbibtex.BibTeXParser.resolveCrossReferences(BibTeXParser.java:113)
	at org.jbibtex.BibTeXParser.Database(BibTeXParser.java:274)
	at org.jbibtex.BibTeXParser.parse(BibTeXParser.java:57)
	at de.undercouch.citeproc.bibtex.BibTeXConverter.loadDatabase(BibTeXConverter.java:149)
	at texlab.completion.bibtex.BibtexCitationActor$actor$1$1.invokeSuspend(BibtexCitationActor.kt:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at texlab.completion.bibtex.BibtexCitationActor$actor$1.invokeSuspend(BibtexCitationActor.kt:17)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by pfoerster** [comment]
The Rust version of the server should not crash anymore when encountering
BibTeX entries with the `crossref` field. However, support for rendering entries
with the `crossref` field is not supported yet.

**Comment by pfoerster** [comment]
The `1.8.0` release of TexLab will support hovering over BibTeX entries with the `crossref` field.
