### ISSUE TITLE
Error: "Request textDocument/documentSymbol failed"

### ISSUE THREAD

**Issue by Majkel1999** [latex-lsp/texlab#870]
When working with a `.tex` document, in uncertain circumstances, the error `Request textDocument/documentSymbol failed` shows up. 

This error mostly shows up when creating a new `.tex` file, which is a part of a bigger document, and starting with a directive such as `\chapter{}'. After saving the document, or when using autosave, the above error is displayed.

```
[Error - 9:56:14 AM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at t.validate (c:\Users\<Redacted>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:25900)
	at new t (c:\Users\<Redacted>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:26195)
	at V (c:\Users\<Redacted>\.vscode\extensions\efoerster.texlab-5.4.0-win32-x64\dist\extension.js:1:213015)
	at c (c:\Users\<Redacted>\.vscode\extensions\efoerster.texlab-5.4.0-win32-x64\dist\extension.js:1:251012)
	at t.map (c:\Users\<Redacted>\.vscode\extensions\efoerster.texlab-5.4.0-win32-x64\dist\extension.js:1:251098)
	at Object.asDocumentSymbols (c:\Users\<Redacted>\.vscode\extensions\efoerster.texlab-5.4.0-win32-x64\dist\extension.js:1:220833)
	at i (c:\Users\<Redacted>\.vscode\extensions\efoerster.texlab-5.4.0-win32-x64\dist\extension.js:1:159487)
	at async n.provideDocumentSymbols (c:\Users\<Redacted>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:32515)
```

TexLab custom settings:
```
    "texlab.build.executable": "tectonic",
    "texlab.build.args": [
      "-X",
      "compile",
      "%f",
      "-Z=shell-escape",
      "--synctex",
      "--keep-logs",
      "--keep-intermediates"
    ],
    "texlab.formatterLineLength": 120,
```

Operating System:
```
Edition	Windows 10 Education
Version	21H2
OS build	19044.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0
```

**Comment by pfoerster** [comment]
@Majkel1999 Thanks for debugging this issue! f8baa932676ecfdb4a2d5100db0340b29006e157 fixes problem.

**Comment by Majkel1999** [comment]
Perfect! Thanks and great work on this extension.
